#!/usr/bin/env python

import subprocess

current_branch = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).rstrip()  # output has a newline at the end
all_branches = subprocess.check_output(['git', 'branch']).rstrip().splitlines()

for branch in all_branches:

	if branch.strip() == 'master' or current_branch.strip() in branch.split():
		continue

	try:
		subprocess.check_call(['git', 'branch', '-D', branch.strip()])
	except subprocess.CalledProcessError:
		print 'Failed to delete branch ' + branch
